/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadlapuntagrupo64.Formularios;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidadlapuntagrupo64.AccesoADatos.*;
import universidadlapuntagrupo64.Entidades.*;


/**
 *
 * @author ariel
 */
public class ConsultaAlumnosPorMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevaConsultaAlumnosPorMateria
     */
    private ArrayList<Materia> listaM;
    private ArrayList<Alumno> listaA; 
    private InscripcionData inscData; 
    private MateriaData mData; 
    private AlumnoData aData; 
    
    private DefaultTableModel modelo = new DefaultTableModel();
    
    
    public ConsultaAlumnosPorMateria() {
        initComponents();
        mData = new MateriaData(); 
        listaM = (ArrayList<Materia>)mData.listarMaterias();
        modelo = new DefaultTableModel();
        inscData = new InscripcionData(); 
        aData = new AlumnoData(); 
        cargarMaterias();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlSeleccionarMateria = new javax.swing.JLabel();
        jcbListaMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaAlumnos = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(56, 133, 188));

        jlTitulo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jlTitulo.setText("Consulta Alumnos por Materia");

        jlSeleccionarMateria.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jlSeleccionarMateria.setText("Seleccionar Materia");

        jcbListaMaterias.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jcbListaMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbListaMateriasActionPerformed(evt);
            }
        });

        jtListaAlumnos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jtListaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtListaAlumnos);

        jbSalir.setBackground(new java.awt.Color(23, 56, 79));
        jbSalir.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlSeleccionarMateria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbListaMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbSalir)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitulo)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSeleccionarMateria)
                    .addComponent(jcbListaMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jbSalir)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbListaMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbListaMateriasActionPerformed
        // TODO add your handling code here:
        cargarDatosAlumnos();
    }//GEN-LAST:event_jcbListaMateriasActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Materia> jcbListaMaterias;
    private javax.swing.JLabel jlSeleccionarMateria;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtListaAlumnos;
    // End of variables declaration//GEN-END:variables
    
    
    private void cargarMaterias(){
        Materia materia = new Materia(); 
        for (Materia item: listaM) {
            jcbListaMaterias.addItem(item);
        }
    }
    
    private void armarCabeceraTabla(){
        ArrayList <Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID Alumno");
        filaCabecera.add("DNI");
        filaCabecera.add("Apellido");
        filaCabecera.add("Nombre");
        for(Object it: filaCabecera){
            modelo.addColumn(it);
        }
        jtListaAlumnos.setModel(modelo);
    }
        
    private void cargarDatosAlumnos(){
        borrarFilasTabla();
        Materia selec = (Materia)jcbListaMaterias.getSelectedItem();
        List<Alumno> lista = (ArrayList) inscData.obtenerAlumnosPorMateria(selec.getidMateria());  //inscData.obtenerInscripcionesPorAlumno(selec.getIdAlumno());
        for(Alumno a: lista){
            modelo.addRow(new Object[] {a.getIdAlumno(), a.getDni(), a.getApellido(), a.getNombre()});
        }
    }
        private void borrarFilasTabla(){
        int indice = modelo.getRowCount() -1;
        for (int i = indice; i>=0; i--){
            modelo.removeRow(i);
        }
    }
}
